services:
  opensora:
    tty: true
    image: opensora:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: opensora
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - ./:/workspace
      - ./ckpts:/workspace/ckpts
      - ./samples:/workspace/samples
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: /bin/bash 